storm/storm/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('wyniki/', include('wyniki.urls')),
    path('aparaty/', include('aparaty.urls')),
    path('soupapi/', include('soupapi.urls')),
    path('admin/', admin.site.urls),
] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

storm/wyniki/urls.py
from django.urls import path

from . import views

app_name = 'wyniki'
urlpatterns = [
    path('rejestracja/', views.rejestracja, name='rejestracja'),
    path('pacjenci/', views.pacjenci, name='pacjenci'),
    path('niepobrane/', views.index_view, {'zakres_dat': 'niepobrane'}, name='index-niepobrane'),
    path('niepobrane/zip/', views.niepobrane_zip, name='niepobrane-zip'),
    path('dzisiaj/', views.index_view, {'zakres_dat': 'dzisiaj'}, name='index-dzisiaj'),
    path('7dni/', views.index_view, {'zakres_dat': '7dni'}, name='index-7dni'),
    path('30dni/', views.index_view, {'zakres_dat': '30dni'}, name='index-30dni'),
    path('rok/', views.index_view, {'zakres_dat': 'rok'}, name='index-rok'),
    path('wszystko/', views.index_view, {'zakres_dat': 'wszystkie'}, name='index-wszystkie'),
    path('zlecenie/<int:numer_zlecenia>/', views.zlecenie_view, name='zlecenie'),
    path('pdf/akceptujpdf/', views.akceptowanie_pdf, name='akceptowanie_pdf'),
    path('pdf/<uuid:wynikpdf_id>/', views.pdf_view, name='wynikpdf'),
    path('pdf/<uuid:wynikpdf_id>/pdf_vote/', views.pdf_vote, name='pdf_vote'),
    ]

storm/wyniki/models.py
import uuid
import binascii
import os, shutil
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage

from PyPDF2 import PdfFileReader

 
class Kontrahent(models.Model):
    nazwa = models.CharField(max_length=100)
    drukowac_wyniki = models.BooleanField(default=False)

    # pola z lab3000
    id_platnika = models.IntegerField()

    def __str__(self):
        return self.nazwa

    class Meta:
        verbose_name_plural = "Płatnicy"

class MyUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT, related_name="myuser")
    kontrahent = models.ForeignKey(Kontrahent, on_delete=models.PROTECT, related_name="myuser")
    pwzdl = models.CharField(max_length=6, blank=True, default='')
    katalog_ps = models.CharField(max_length=3, blank=True, default='')

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = "Użytkownicy"

class Pacjent(models.Model):
    imie = models.CharField(max_length=200, null=True, blank=True)
    nazwisko = models.CharField(max_length=200, null=True, blank=True)
    pesel = models.CharField(max_length=20, null=True, blank=True)
    data_urodzenia = models.DateField(null=True, blank=True)
    
    # pola z lab3000
    id_pacjenta = models.IntegerField()
    miejsce_zam = models.CharField(max_length=200, null=True, blank=True)

    @property
    def nazwa(self):
        return self.imie + ' ' + self.nazwisko

    def __str__(self):
        data_urodzenia = self.data_urodzenia.strftime("%Y-%m-%d") if self.data_urodzenia else 'nie podano'
        pesel_lub_rok = self.pesel if self.pesel else data_urodzenia
        adres = self.miejsce_zam if self.miejsce_zam else 'nie podano'
        return '{nazwisko} {imie} ({pesel}) adres: {adres}'.format(imie=self.imie,
                nazwisko=self.nazwisko,
                pesel=pesel_lub_rok,
                adres=adres)

    class Meta:
        verbose_name_plural = "Pacjenci"

class Zlecenie(models.Model):
    numer = models.IntegerField()
    zlecone = models.DateTimeField()
    pacjent = models.ForeignKey(Pacjent, on_delete=models.PROTECT)
    owner = models.ForeignKey(Kontrahent, on_delete=models.PROTECT)
    created = models.DateTimeField(auto_now_add=True)
    na_dzien = models.DateTimeField(blank=True, null=True, default=None)
    zrealizowane = models.DateTimeField(blank=True, null=True, default=None)
    anulowane = models.BooleanField(default=False)

    # pola z lab3000
    id_zlecenia = models.IntegerField()

    def __str__(self):
        return str(self.numer)


    class Meta:
        ordering = ['-created']
        verbose_name_plural = "Zlecenia"


class GrupaBadan(models.Model):
    nazwa = models.CharField(max_length=200)
    nazwa_krotka = models.CharField(max_length=50)
    id_badania = models.IntegerField(null=True)

    def __str__(self):
        return str(self.nazwa)

    class Meta:
        verbose_name_plural = "Grupy Badań"

class Badanie(models.Model):
    nazwa = models.CharField(max_length=200)
    nazwa_krotka = models.CharField(max_length=50)
    icd = models.CharField(max_length=10, blank=True, default='')
    children = models.ManyToManyField('self')
    grupabadan = models.ForeignKey(GrupaBadan, blank=True, null=True, default=None, on_delete=models.PROTECT)
    zlec_w_calosci = models.BooleanField(default=False)
    jednostka = models.CharField(max_length=20, blank=True, default='')

    # pola z lab3000
    id_badania = models.IntegerField(null=True)

    def __str__(self):
        return str(self.nazwa_krotka)

    class Meta:
        verbose_name_plural = "Badania"


class WartosciReferencyjne(models.Model):
    od = models.CharField(max_length=10, blank=True, default ='')
    do = models.CharField(max_length=10, blank=True, default ='')
    wydruk = models.CharField(max_length=50, blank=True, default ='')

    # pola z lab3000
    id_tabeli = models.IntegerField()

    def __str__(self):
        return str(self.wydruk)

    class Meta:
        verbose_name_plural = "Wartości referencyjne"


class Probka(models.Model):
    numer = models.CharField(max_length=20, blank=True, default='')
    pobrana = models.DateTimeField(blank=True, null=True, default=None)
    
    def __str__(self):
        return self.numer

    class Meta:
        verbose_name_plural = "Próbki"

class WynikManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(parent=None)

class Wynik(models.Model):
    badanie = models.ForeignKey(Badanie, on_delete=models.PROTECT, related_name="wynik_badanie")
    grupa = models.ForeignKey(GrupaBadan, on_delete=models.PROTECT, related_name="wynik_grupa")
    zlecenie = models.ForeignKey(Zlecenie, on_delete=models.PROTECT, related_name="wyniki")
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name="children")
    probka = models.ForeignKey(Probka, on_delete=models.PROTECT, null=True, blank=True, default=None)
    wartosci_referencyjne = models.ForeignKey(WartosciReferencyjne, on_delete=models.PROTECT, blank=True, null=True)
    tekstowy = models.CharField(max_length=50, blank=True, default='')
    flaga = models.CharField(max_length=1, blank=True, default='')
    wykonany = models.DateTimeField(blank=True, null=True, default=None)
    odprawiony = models.DateTimeField(blank=True, null=True, default=None)
    wydrukowany = models.DateTimeField(blank=True, null=True, default=None)
    anulowany = models.BooleanField(default=False)
    gotowy_do_hl7 = models.BooleanField(default=False)
    wyslany_do_hl7 = models.BooleanField(default=False)
    # pola z lab3000
    id_tabeli = models.IntegerField(blank=True, null=True, default=None)

    #managers
    #badania_etykiety = WynikManager()

    def __str__(self):
        if self.tekstowy:
            jednostka = '[{}]'.format(self.badanie.jednostka) if self.badanie.jednostka else ''
            return '{wynik} {jednostka}'.format(wynik=self.tekstowy, jednostka=jednostka)
        else:
            return ''

    class Meta:
        ordering = ['badanie__nazwa_krotka']
        verbose_name_plural = "Wyniki"


class WynikPDF(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    anulowany = models.BooleanField(default=False)
    do_sprawdzenia = models.BooleanField(default=True)
    sprawdzony = models.BooleanField(default=False)
    podpisany = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    wydrukowany = models.DateTimeField(null=True)
    pdf = models.FileField(null=True, upload_to='pdf/%Y/%m/%d/')
    ps = models.FileField(null=True, upload_to='ps/')
    zlecenie = models.ForeignKey(Zlecenie, on_delete=models.PROTECT)
    owner = models.ForeignKey(User, null=True, on_delete=models.PROTECT)
    pobrany = models.BooleanField(default=False)
    wyniki = models.ManyToManyField(Wynik)

    def przenies_do_podpisania(self):
        user_folder = self.owner.myuser.katalog_ps
        nazwa = str(self.id) + '.ps'
        new_path = os.path.join(settings.PS_IN, user_folder, nazwa)
        shutil.copy2(self.pdf.path, new_path)
        self.do_sprawdzenia = False
        self.sprawdzony = True   
    
    class Meta:
        ordering = ['created']
        verbose_name_plural = "Wyniki PDF"
  

class WynikPNG(models.Model):
    pdf = models.ForeignKey(WynikPDF, on_delete=models.CASCADE, related_name="img")
    img = models.ImageField(upload_to='img/%Y/%m/%d')
    
    class Meta:
        verbose_name_plural = "Wynik PNG"

storm/wyniki/forms.py
from django import forms

class PacjentForm(forms.Form):
    imie = forms.CharField(label='Imię pacjenta', max_length=100)

storm/wyniki/views.py
import datetime
import urllib
import os
from io import BytesIO
from zipfile import ZipFile
import logging

from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from .models import Zlecenie, WynikPDF, WynikPNG, Wynik, Pacjent
from .forms import PacjentForm

logger = logging.getLogger(__name__)


@login_required
def rejestracja(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PacjentForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            print(request.POST)
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect(reverse('wyniki:rejestracja'))        

    # if a GET (or any other method) we'll create a blank form
    else:
        form = PacjentForm()

    return render(request, 'wyniki/rejestracja.html', {'form': form})

@login_required
def pacjenci(request):
    q = request.GET.get('q', None)
    qs = Pacjent.objects.all()
    for term in q.split():
        qs = qs.filter( Q(nazwisko__icontains = term) | Q(imie__icontains = term) | Q(pesel__icontains = term))
    lista = []
    for p in qs:
        lista.append({'id': p.id, 'text': p.__str__()})
    response = JsonResponse(
            {"results": lista,"pagination": {"more": True}},
            safe=False
            )
    return response

@login_required
def index_view(request, zakres_dat):
    context = {}
    teraz = timezone.now()
    dzis = teraz.replace(hour=0, minute=0, second=0, microsecond=0)
    jutro = dzis + datetime.timedelta(days=1)
    tydzien = dzis - datetime.timedelta(days=7)
    miesiac = dzis - datetime.timedelta(days=30)
    rok = dzis.replace(month=1, day=1)
    l = Zlecenie.objects.all().prefetch_related('wyniki')
    if not request.user.is_staff:
        l = l.filter(owner__myuser__user=request.user)
    if zakres_dat == 'niepobrane':
        l = l.filter(owner__myuser__user=request.user)
        l = l.filter(wynikpdf__pobrany=False, wynikpdf__podpisany=True).distinct()
    elif zakres_dat == 'dzisiaj':
        l = l.filter(na_dzien__gte=dzis, na_dzien__lte=teraz)
    elif zakres_dat == '7dni':
        l = l.filter(na_dzien__gte=tydzien, na_dzien__lte=teraz)
    elif zakres_dat == '30dni':
        l = l.filter(na_dzien__gte=miesiac, na_dzien__lte=teraz)
    elif zakres_dat == 'rok':
        l = l.filter(na_dzien__gte=rok, na_dzien__lte=teraz)
    elif zakres_dat == 'wszystkie':
        l = l
    context['tekst_wyszukiwania'] = ''
    context['zakres_dat'] = zakres_dat
    context['urlparams'] = urllib.parse.urlencode(request.GET)
    q = request.GET.get('q', None)    
    if q:
        context['tekst_wyszukiwania'] = q
        l1 = Zlecenie.objects.none()
        try:
            i = int(q)
            l1 = l.filter(numer__exact=i)
        except Exception as e:
            pass
        if not l1:
            for term in q.split():
                l = l.filter( Q(pacjent__nazwisko__icontains = term) | Q(pacjent__imie__icontains = term) | Q(pacjent__pesel__icontains = term))
        else:
            l = l1
    # ustawienia podziału wyświetlanej strony
    paginator = Paginator(l, 20)
    page = request.GET.get('page')
    zlecenia = paginator.get_page(page)
    context['lista_zlecen'] = zlecenia
    
    return render(request, 'wyniki/index.html', context)

@login_required
def zlecenie_view(request, numer_zlecenia):
    zlecenie = get_object_or_404(Zlecenie, numer=numer_zlecenia)
    
    w_all = zlecenie.wyniki.all() if zlecenie else None
    wyniki = zlecenie.wyniki.filter(parent=None) if zlecenie else None
    print(type(wyniki))
    for w in wyniki:
        print(w.badanie.nazwa)
        print(w.children.all())    
    return render(request, 'wyniki/zlecenie.html', {'zlecenie': zlecenie, 'wyniki': wyniki})


@login_required
def pdf_view(request, wynikpdf_id):
    # Create the HttpResponse object with the appropriate PDF headers.
    pdf_file = WynikPDF.objects.get(pk=wynikpdf_id)
    response = HttpResponse(pdf_file.pdf, content_type='application/pdf')
    name = pdf_file.pdf.name.split('/')[-1]
    response['Content-Disposition'] = 'attachment; filename={}'.format(name)
    pdf_file.pobrany = True
    pdf_file.save()
    return response

@login_required
def niepobrane_zip(request):
    # Files (local path) to put in the .zip
    # FIXME: Change this (get paths from DB etc)
    filenames = []
    pdfs = WynikPDF.objects.filter(zlecenie__owner__myuser__user=request.user, pobrany=False, podpisany=True)
    for f in pdfs:
        filenames.append(f.pdf.path)
        logger.debug(f.pdf.path)
    # Folder name in ZIP archive which contains the above files
    # E.g [thearchive.zip]/somefiles/file2.txt
    # FIXME: Set this to something better
    zip_filename = "wyniki.zip"
    # Open StringIO to grab in-memory ZIP contents
    s = BytesIO()
    # The zip compressor
    zf = ZipFile(s, "w")
    for fpath in filenames:
        # Calculate path for file in zip
        fdir, fname = os.path.split(fpath)
        # Add file, at correct path
        zf.write(fpath, fname)
    # Must close zip for all contents to be written
    zf.close()
    # Grab ZIP file from in-memory, make response with correct MIME-type
    response = HttpResponse(s.getvalue(), content_type = "application/x-zip-compressed")
    # ..and correct content-disposition
    response['Content-Disposition'] = 'attachment; filename={}'.format(zip_filename)
    pdfs.update(pobrany=True)
    return response

@login_required
def akceptowanie_pdf(request):
    if request.user.is_staff:
        context = {}
        l = WynikPDF.objects.order_by('created').prefetch_related('img')
        l = l.filter(do_sprawdzenia=True)
        do_sprawdzenia_ogolnie = l.count()
        l = l.filter(owner=request.user)
        do_sprawdzenia_user = l.count()
        l = l.first()
        w = l.wyniki.filter(anulowany=False) if l else None
        context = {'obrazek': l, 'wyniki': w,'do_sprawdzenia_ogolnie': do_sprawdzenia_ogolnie, 'do_sprawdzenia_user': do_sprawdzenia_user}
        return render(request, 'wyniki/akceptowanie_pdf.html', context)

@login_required
def pdf_vote(request, wynikpdf_id):
    try:
        pdf = get_object_or_404(WynikPDF, pk=wynikpdf_id)
        if request.POST.get('ok'):
            pdf.przenies_do_podpisania()
            pdf.save()
            return HttpResponseRedirect(reverse('wyniki:akceptowanie_pdf'))        
        elif request.POST.get('nie'):
            pdf.do_sprawdzenia = False
            pdf.anulowany = True
            pdf.save()
            return HttpResponseRedirect(reverse('wyniki:akceptowanie_pdf'))  
    except (KeyError, WynikPDF.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'wyniki/akceptowanie_pdf.html', {
            'error_message': "You didn't select a choice.",
        })

storm/wyniki/templates/wyniki/index.html
{% extends 'base.html' %}
{% load static %}


{% block content-opcje %}
          <div class="col-sm-6 pull-right">
            <nav class="clearfix">
              <ul class="list-inline pull-right small">
                
                {% if zakres_dat == "niepobrane" %}
                  <li role="presentation"><a class="zielony" href="{% url 'wyniki:index-niepobrane' %}"><strong>niepobrane</strong></a></li>
                {% else %}
                  <li role="presentation"><a class="zielony" href="{% url 'wyniki:index-niepobrane' %}">niepobrane</a></li>
                {% endif %}
                
                {% if zakres_dat == "dzisiaj" %}
                  <li role="presentation"><a class="zielony" href="{% url 'wyniki:index-dzisiaj' %}"><strong>dzisiaj</strong></a></li>
                {% else %}
                  <li role="presentation"><a class="zielony" href="{% url 'wyniki:index-dzisiaj' %}">dzisiaj</a></li>
                {% endif %}
                
                {% if zakres_dat == "7dni" %}
                  <li role="presentation"><a class="zielony" href="{% url 'wyniki:index-7dni' %}"><strong>ostatnie 7 dni</strong></a></li>
                {% else %}
                  <li role="presentation"><a class="zielony" href="{% url 'wyniki:index-7dni' %}">ostatnie 7 dni</a></li>
                {% endif %}

                {% if zakres_dat == "30dni" %}
                  <li role="presentation"><a class="zielony" href="{% url 'wyniki:index-30dni' %}"><strong>ostatnie 30 dni</strong></a></li>
                {% else %}
                  <li role="presentation"><a class="zielony" href="{% url 'wyniki:index-30dni' %}">ostatnie 30 dni</a></li>
                {% endif %}

                {% if zakres_dat == "rok" %}
                  <li role="presentation"><a class="zielony" href="{% url 'wyniki:index-rok' %}"><strong>bieżący rok</strong></a></li>
                {% else %}
                  <li role="presentation"><a class="zielony" href="{% url 'wyniki:index-rok' %}">bieżący rok</a></li>
                {% endif %}

                {% if zakres_dat == "wszystkie" %}
                  <li role="presentation"><a class="zielony" href="{% url 'wyniki:index-wszystkie' %}"><strong>wszystkie</strong></a></li>
                {% else %}
                  <li role="presentation"><a class="zielony" href="{% url 'wyniki:index-wszystkie' %}">wszystkie</a></li>
                {% endif %}

              </ul>
            </nav>
            <nav class="clearfix">
              <form class="pull-right" role="search">
                <div class="input-group">
                    <input type="text" class="form-control" value="{{ tekst_wyszukiwania }}" placeholder="Pesel, nazwisko lub imię" name="q">
                    <div class="input-group-btn">
                      <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                    </div>
                </div>
              </form>
            </nav>
          </div>
{% endblock content-opcje %}



{% block title-nazwa %}Zestawienie zleceń{% endblock title-nazwa %}



{% block content %}

{% if lista_zlecen %}
<div>
{% if zakres_dat == "niepobrane" %}
<a class="zielony" href="{% url 'wyniki:niepobrane-zip' %}"><strong>Pobierz wszystkie jako zip</strong></a>
{% endif %}
</div>
<table class="table table-sm table-borderless table-hover">
  <colgroup>
    <col class="col-sm-2">
    <col class="col-sm-4">
    <col class="col-sm-1">
    <col class="col-sm-5">

  </colgroup>
  <thead>
    <tr>
      <th scope="col">Data</th>
      <th scope="col">Pacjent</th>
      <th scope="col">Zlecenie</th>
      <th scope="col">Badania</th>
    </tr>
  </thead>
  <tbody>
{% for zlecenie in lista_zlecen %}
    <tr>
      <td>{{ zlecenie.na_dzien|date:"SHORT_DATE_FORMAT" }}</td>
      <td>{{ zlecenie.pacjent|title  }}</td>
      <td>
        <a class="zielony" href="{% url 'wyniki:zlecenie' zlecenie.numer %}">{{ zlecenie.numer }}</a>
      </td>
      <td class="small">

          {% regroup zlecenie.wyniki.all by grupa as badania_list %}
          {% for wynik in badania_list  %}

              {% for badanie in wynik.list %}
                {% if not badanie.parent %}
                  {{ badanie.badanie }}{% if not forloop.last  %}, {% endif  %}
                {% endif  %}
              {% endfor %}
          {% endfor %}

      </td>
    </tr>
{% endfor %}

  </tbody>
</table>
{% else %}
    <p>Brak zleceń.</p>
{% endif %}
    <div class="row">
            <nav>
              <ul class="list-inline text-center small">
                
        {% if tekst_wyszukiwania %}
        {% if lista_zlecen.has_previous %}
        <li role="presentation"><a class="zielony" href="?q={{ tekst_wyszukiwania }}&amp;page=1">&laquo; pierwsza</a></li>
                  <li role="presentation"><a class="zielony" href="?q={{ tekst_wyszukiwania }}&amp;page={{ lista_zlecen.previous_page_number }}">poprzednia</a></li>
        {% endif %}
                  <li role="presentation">Strona {{ lista_zlecen.number }} z {{ lista_zlecen.paginator.num_pages }}</li>
        {% if lista_zlecen.has_next %}
                  <li role="presentation"><a class="zielony" href="?q={{ tekst_wyszukiwania }}&amp;page={{ lista_zlecen.next_page_number }}">następna</a></li>
                  <li role="presentation"><a class="zielony" href="?q={{ tekst_wyszukiwania }}&amp;page={{ lista_zlecen.paginator.num_pages }}">ostatnia &raquo;</a></li>
        {% endif %}
        {% else  %}

        {% if lista_zlecen.has_previous %}
                  <li role="presentation"><a class="zielony" href="?page=1">&laquo; pierwsza</a></li>
                  <li role="presentation"><a class="zielony" href="?page={{ lista_zlecen.previous_page_number }}">poprzednia</a></li>
        {% endif %}
                  <li role="presentation">Strona {{ lista_zlecen.number }} z {{ lista_zlecen.paginator.num_pages }}</li>
        {% if lista_zlecen.has_next %}
                  <li role="presentation"><a class="zielony" href="?page={{ lista_zlecen.next_page_number }}">następna</a></li>
                  <li role="presentation"><a class="zielony" href="?page={{ lista_zlecen.paginator.num_pages }}">ostatnia &raquo;</a></li>
        {% endif %}

        {% endif %}
              </ul>
            </nav>
        </div>
            

{% endblock content %}

storm/wyniki/templates/wyniki/zlecenie.html
{% extends 'base.html' %}
{% load static %}

{% block title-nazwa %}{{ zlecenie.pacjent|title }}{% endblock title-nazwa %}



{% block content %}
<p>Zlecenie numer: {{ zlecenie.numer }} z {{ zlecenie.zlecone|date:"SHORT_DATETIME_FORMAT"  }} przyjęte {{ zlecenie.na_dzien|date:"SHORT_DATETIME_FORMAT"  }}</p>
<p>Zlecone badania:</p>
<div class="row">
<div class="col-sm-10">
<table class="table table-sm table-borderless small table-hover">
  <colgroup>
    <col class="col-sm-4">
    <col class="col-sm-2">
    <col class="col-sm-1">
    <col class="col-sm-2">
    <col class="col-sm-1">
    <col class="col-sm-2">

  </colgroup>
  <thead>
    <tr>
      <th scope="col">Badanie</th>
      <th scope="col">Wynik</th>
      <th scope="col">Flaga</th>
      <th scope="col">Zakres wartości</th>
      <th scope="col">Anulowany</th>
      <th scope="col">Zatwierdzony</th>
    </tr>
  </thead>
  <tbody>
    {% for wynik in wyniki %}
        {% if wynik.anulowany %}
        <tr class='warning'>
        {% elif wynik.flaga == 'H' %}
        <tr class='czerwony'>
        {% elif wynik.flaga == 'L' %}
        <tr class='niebieski'>
        {% else %}
        <tr>
      {% endif %}
        <td>{{ wynik.badanie.nazwa }} </td>
        <td>{% if wynik.odprawiony %}{{ wynik }}{% endif %}</td>
        <td>{{wynik.flaga }} </td>
        <td>{{wynik.wartosci_referencyjne.wydruk}} </td>
        <td>{% if wynik.anulowany %} anulowany {% endif %} </td>
        <td>{{wynik.odprawiony|date:"SHORT_DATETIME_FORMAT"}} </td>
    </tr>

    {% for w in wynik.children.all %}
                {% if w.anulowany %}
                <tr class='warning'>
                {% elif w.flaga == 'H' %}
                <tr class='czerwony'>
                {% elif w.flaga == 'L' %}
                <tr class='niebieski'>
                {% else %}
                <tr>
              {% endif %}
                <td>&emsp;{{ w.badanie.nazwa }}</td>
                <td>{% if w.odprawiony %}{{ w }}{% endif %}</td>
                <td>{{w.flaga }} </td>
                <td>{{w.wartosci_referencyjne.wydruk}} </td>
                <td>{% if w.anulowany %} anulowany {% endif %} </td>
                <td>{{w.odprawiony|date:"SHORT_DATETIME_FORMAT"}} </td>
            </tr>
    {% endfor %}

    {% endfor %}

  </tbody>
</table>
                            </div>

                </div>


<p>Wyniki w formie pdf:</p>
{% for pdf in zlecenie.wynikpdf_set.all %}
    {% if pdf.podpisany %}
        {% if not pdf.anulowany%}
        <p>
        <a class="zielony" href="{% url 'wyniki:wynikpdf' pdf.pk  %}"><i class="fa fa-file-pdf-o fa-lg"></i></a>
        Utworzony {{ pdf.created|date:"SHORT_DATETIME_FORMAT" }}
        {% if not pdf.pobrany %}(nowy){% endif %}
        </p>
        {% else %}
            <p>Utworzony {{ pdf.created|date:"SHORT_DATETIME_FORMAT" }}  <a class="czerwony" href=""><i class="fa fa-file-pdf-o fa-lg"></i></a> anulowany</p>
        {% endif %}
    {% endif %}
{% endfor %}


{% endblock content %}